type PackageManifest = {
  readonly name: string
  readonly version: string
  readonly packageManager?: string
  readonly license?: string
  readonly repository?: string | { readonly url?: string }
  readonly homepage?: string
  readonly dependencies?: Readonly<Record<string, string>>
}

type DependencyScope = "control-plane-and-runner" | "cloudflare-bridge"

type PackageNotice = {
  readonly id: string
  readonly license: string
  readonly licenseText: string | undefined
  readonly source: string | undefined
  readonly scopes: Set<DependencyScope>
}

const repositoryRoot = process.cwd()
const noticePath = `${repositoryRoot}/THIRD_PARTY_NOTICES`
const licenseCandidates = [
  "LICENSE",
  "LICENSE.md",
  "LICENSE.txt",
  "LICENCE",
  "LICENCE.md",
  "LICENCE.txt",
] as const

const packageScopes = [
  {
    name: "control-plane-and-runner" as const,
    packagePath: `${repositoryRoot}/package.json`,
    resolveFrom: repositoryRoot,
  },
  {
    name: "cloudflare-bridge" as const,
    packagePath: `${repositoryRoot}/providers/cloudflare-sandbox/package.json`,
    resolveFrom: `${repositoryRoot}/providers/cloudflare-sandbox`,
  },
]

const expected = await renderNotices()
const mode = process.argv[2]

if (mode === "--write") {
  await Bun.write(noticePath, expected)
  console.log(`wrote ${noticePath}`)
} else if (mode === "--check") {
  const actual = await Bun.file(noticePath)
    .text()
    .catch(() => "")
  if (actual !== expected) {
    console.error("THIRD_PARTY_NOTICES is stale; run `bun run notices:generate`.")
    process.exit(1)
  }
  console.log("THIRD_PARTY_NOTICES matches installed production dependency graphs.")
} else {
  console.error("usage: bun scripts/third-party-notices.ts --write|--check")
  process.exit(2)
}

async function renderNotices(): Promise<string> {
  const notices = new Map<string, PackageNotice>()
  const projectManifest = await readManifest(`${repositoryRoot}/package.json`)
  const bunVersion = projectManifest.packageManager?.match(/^bun@(\d+\.\d+\.\d+)$/)?.[1]
  if (!bunVersion) throw new Error("packageManager must pin an exact Bun version")
  if (Bun.version !== bunVersion) {
    throw new Error(`notice generation requires Bun ${bunVersion}, received ${Bun.version}`)
  }
  const bunLicensePath = `${repositoryRoot}/licenses/BUN-${bunVersion}-LICENSE.md`
  const bunLicense = (await Bun.file(bunLicensePath).text()).trim()

  for (const scope of packageScopes) {
    const manifest = await readManifest(scope.packagePath)
    const pending = Object.keys(manifest.dependencies ?? {}).map((name) => ({
      name,
      resolveFrom: scope.resolveFrom,
    }))
    const visited = new Set<string>()

    while (pending.length > 0) {
      const dependency = pending.shift()
      if (!dependency) break

      const packageRoot = await resolvePackageRoot(dependency.name, dependency.resolveFrom)
      const packageManifest = await readManifest(`${packageRoot}/package.json`)
      const id = `${packageManifest.name}@${packageManifest.version}`
      if (visited.has(id)) continue
      visited.add(id)

      const existing = notices.get(id)
      if (existing) {
        existing.scopes.add(scope.name)
      } else {
        const license = packageManifest.license?.trim()
        if (!license) throw new Error(`${id} does not declare a license`)
        notices.set(id, {
          id,
          license,
          licenseText: await readLicenseText(packageRoot),
          source: sourceUrl(packageManifest),
          scopes: new Set([scope.name]),
        })
      }

      for (const child of Object.keys(packageManifest.dependencies ?? {})) {
        pending.push({ name: child, resolveFrom: packageRoot })
      }
    }
  }

  const packages = [...notices.values()].sort((left, right) => left.id.localeCompare(right.id))
  const lines = [
    "THIRD-PARTY SOFTWARE NOTICES",
    "",
    "Generated by `bun run notices:generate` from the installed production dependency",
    "graphs pinned by bun.lock. `bun run notices:check` fails when this file drifts.",
    "",
    "The inventory covers JavaScript packages distributed by the Meanwhile control plane,",
    "standalone runner, and Cloudflare Worker bridge. Platform images are separately pinned",
    "distribution inputs and retain their own authoritative package inventories and terms:",
    "",
    `- oven/bun:${bunVersion}-slim (Bun runtime plus its Debian base)`,
    "- cloudflare/sandbox:0.12.3 (Cloudflare Sandbox runtime image)",
    "",
    "The root image additionally installs Debian ca-certificates and Git. This notice does not",
    "pretend to reproduce an image SBOM; release review must inspect the exact image provenance",
    "and upstream license material alongside this application-level inventory.",
    "",
    "DEPENDENCY INVENTORY",
    "",
  ]

  for (const item of packages) {
    const scopes = [...item.scopes].sort().join(", ")
    const source = item.source ? `; ${item.source}` : ""
    lines.push(`- ${item.id} — ${item.license} — ${scopes}${source}`)
  }

  const groupedTexts = new Map<string, { packages: string[]; text: string }>()
  const missingTexts: PackageNotice[] = []
  for (const item of packages) {
    if (!item.licenseText) {
      missingTexts.push(item)
      continue
    }
    const group = groupedTexts.get(item.licenseText)
    if (group) group.packages.push(item.id)
    else groupedTexts.set(item.licenseText, { packages: [item.id], text: item.licenseText })
  }

  lines.push("", "LICENSE TEXTS")
  for (const group of [...groupedTexts.values()].sort((left, right) =>
    left.text.localeCompare(right.text),
  )) {
    lines.push("", `Applies to: ${group.packages.sort().join(", ")}`, "", group.text)
  }

  if (missingTexts.length > 0) {
    lines.push(
      "",
      "PACKAGES WHOSE PUBLISHED ARCHIVE OMITTED A LICENSE FILE",
      "",
      "The following installed package archives declare the shown SPDX expression in",
      "package.json but contain no standalone license text. Their identity, declaration, and",
      "upstream source are preserved here rather than inventing an attribution:",
      "",
    )
    for (const item of missingTexts) {
      lines.push(`- ${item.id} — ${item.license}${item.source ? ` — ${item.source}` : ""}`)
    }
  }

  lines.push(
    "",
    `BUN ${bunVersion} RUNTIME NOTICE`,
    "",
    `The control-plane image and standalone compiled executables contain Bun ${bunVersion}.`,
    "The following text is preserved from the exact upstream tag",
    `https://github.com/oven-sh/bun/blob/bun-v${bunVersion}/LICENSE.md:`,
    "",
    bunLicense,
  )

  return `${lines.join("\n").trimEnd()}\n`
}

async function resolvePackageRoot(name: string, resolveFrom: string): Promise<string> {
  let candidate = Bun.resolveSync(name, resolveFrom)
  while (!(await Bun.file(`${candidate}/package.json`).exists())) {
    const parent = parentPath(candidate)
    if (parent === candidate) throw new Error(`could not locate package.json for ${name}`)
    candidate = parent
  }
  return candidate
}

async function readManifest(path: string): Promise<PackageManifest> {
  return (await Bun.file(path).json()) as PackageManifest
}

async function readLicenseText(packageRoot: string): Promise<string | undefined> {
  for (const candidate of licenseCandidates) {
    const file = Bun.file(`${packageRoot}/${candidate}`)
    if (await file.exists()) return (await file.text()).replaceAll("\r\n", "\n").trim()
  }
  return undefined
}

function sourceUrl(manifest: PackageManifest): string | undefined {
  const repository =
    typeof manifest.repository === "string" ? manifest.repository : manifest.repository?.url
  const value = repository ?? manifest.homepage
  if (!value) return undefined
  const normalized = value.replace(/^git\+/, "").replace(/\.git$/, "")
  if (normalized.startsWith("github:")) {
    return `https://github.com/${normalized.slice("github:".length)}`
  }
  if (/^[\w.-]+\/[\w./-]+$/.test(normalized)) return `https://github.com/${normalized}`
  return normalized.replace(/^git:\/\//, "https://")
}

function parentPath(path: string): string {
  const separator = path.lastIndexOf("/")
  return separator <= 0 ? "/" : path.slice(0, separator)
}
